version: '3.4'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      #   condition: service_healthy
    environment:
      # This hostname must match the service name defined below
      MONGODB_URI: mongodb://root:example@mongodb:27017/test?authSource=admin
    restart: always

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p example
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081" # The web interface will be accessible on this port
    depends_on:
      - mongodb
      #   condition: service_healthy # Wait until mongodb reports as healthy
    environment:
      # Connect to the MongoDB instance using the service name
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # These credentials must match the root user set for MongoDB
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
volumes:
  mongo-data:
